add functions
AlexAfanasiev1980/algososh pull request #1
Opened 2022-09-17 09:30 UTC by AlexAfanasiev1980

2022-09-17 11:51 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Хорошая работа!**

### **Но есть несколько замечаний, которые нужно исправить:**

- Во многих файлах 'магические' значение не вынесены в константы. Нужно это исправить.

  "Магические" значения это - такие значения в коде, смысл которых понятен только написавшему их программисту. Например, иногда в интернет-магазинах цену товара автоматически умножают на 1.2, вместо того чтобы ввести понятную переменную для НДС. И без комментариев такие коэффициенты понять очень сложно.

- В коде очень много дублирования кода, а также больших условий, проверьте еще раз, и где это возможно вынести дублирующийся код и большие условия в отдельные функции.

- На странице "Связный список" нет валидации на пустое значение, поэтому если нажать на "добавить в head" или "добавить в tail", и при этом в поле значения будет пустой символ, то список перестанет отображаться.

- Нужно проверить не осталось ли, лишних файлов, которые остались при инициализации create-react-app. (Директория: `App`)

- На странице "Последовательность Фибоначчи" по чек-листу, должна быть реализована функция `getFibonacciNumbers`, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи;

- На странице "Стек" нужно реализовать класс Stack с методами push, pop, clear является дженериком. Он принимает тип элементов, хранящихся в стеке. Для отображения стека в классе Stack должны быть дополнительные методы для получения данных. Например, геттеры elements и size, которые возвращают массив элементов стека и его текущий размер;

- На странице "Очередь" нужно реализовать класс Queue с методами enqueue, dequeue, clear является дженериком. Он принимает тип элементов, хранящихся в очереди. Для отображения очереди в классе Queue должны быть дополнительные методы для получения данных, например, геттеры isEmpty, elements, head и tail.

- функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы `utils.ts` в папке соответствующего компонента;

- классы, описывающие работу структур данных, вынесены в отдельные файлы в папке соответствующего компонента.

- Основные критические моменты были описаны в файле `list-page.tsx`, далее во всём проекте идут очень похожие проблемы, пожалуйста ещё раз перепроверьте и исправьте остальные файлы тоже.

- У вас есть файл констант с таймингами, но вы их не везде используете.

### **Сделает код лучше:**

- Также заметил что на странице "Связный список", при удалении элемента по индексу, удаляемый элемент не выделяется, а сразу уходит вниз. По заданию это должно работать следующим образом:
  При удалении элемента по индексу сначала необходимо выделять цветом элементы, пока не достигнем нужного индекса. Затем очистить значение в элементе и снизу отобразить маленький кружок с удаляемым значением.

  Например, вы ввели индекс 2 и нажали «Удалить по индексу». Сначала цветом выделяется элемент с индексом 0, потом с индексом 1, 2, и только после этого, мы удаляем элемент из связного списка.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами, это затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил что иконки выполнены как компоненты, не могу сказать что это неправильно, но и без причины этого делать не стоит, если вы хотите использовать svg элементы инлайново, для этого можно импортировать их в качестве ReactComponent: https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs.

**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    }
**Можно лучше:** При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +            }
**Можно лучше:** Можно упростить выражение до 1 строчки, используя, тернарный оператор.
```js
const classText = index === arr.length - 1 || index === 9 ? "item1" : "item";
``` 

Также вместо margin, в стилях, можно использовать просто gap у контейнера. Вот неплохая статья: https://css-tricks.com/almanac/properties/g/gap/

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +              <div className={styles[classText]}>
**Надо исправить:** Элементам списка нужно задавать key, он помогает понять реакту, что элементы перемещаются в списке. 
Подробнее: https://ru.react.js.org/docs/lists-and-keys.html#%D0%9A%D0%BB%D1%8E%D1%87%D0%B8

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/list-page/list-page.node.tsx
> +import { createSecureContext } from "tls";
**Можно лучше:**  Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/list-page/list-page.node.tsx
> +      const node = new Nodes(element);
**Можно лучше:**
При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/list-page/list-page.node.tsx
> +    }
**Можно лучше:**
При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +  const [loaderDelTail, setLoaderDelTail] = useState<boolean>(false);
**Надо исправить:** Думаю тут лучше подошел бы объект, или несколько объектов, подумайте как грамотно разбить. Т.к при каждом изменении переменной из этого списка, будет происходить ререндер, и это будет не очень оптимизированно, с учётом того , сколько всего у вас манипуляций.

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    }
**Можно лучше:** Вроде бы тут можно все в 1 цикле сделать.
```js
  for (let i = 0; i < random; i++) {
    const value = Math.floor(Math.random() * 100);
    arr.push(value);
    list.append(value);
  }
```

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +      if (current.value !== null) {
**Можно лучше:** Можно объединить условия, с помощью логического "И". https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Logical_AND

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    }
**Надо исправить:** Попробуйте максимально оптимизировать этот участок. Это можно сделать с помощью тернарного оператора. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +            }
**Надо исправить:** Подумайте, как можно оптимизировать этот участок кода, в частности сократить количество условий. Если все же этого сделать нельзя, то вынесите большие условия в отдельные функции или переменные. Так вы повысите читабельность кода.

2022-09-17 11:51 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +              <li key={uuidv4()} className={styles.item_li}>
**Надо исправить:** Такая генерация key, может вызвать ошибку, т.к при каждом ререндере key будет всегда новый. Каждый раз, когда изменяется ключ компонента, React будет [создавать новый экземпляр компонента, а не обновлять текущий](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key) , поэтому для повышения производительности использование Math.random() будет, мягко говоря, неоптимальным.

Кроме того, если вы каким-либо образом переупорядочиваете свой список компонентов, использование индекса в качестве ключа также не будет полезным, поскольку согласовщик React не сможет просто перемещаться по существующим узлам DOM, связанным с компонентами, вместо этого ему придется повторно -создать DOM-узлы для каждого элемента списка, которые, опять же, будут иметь неоптимальную производительность.

Но повторюсь, это будет проблемой только в том случае, если вы будете переупорядочивать список, поэтому в вашем случае, если вы уверены, что не будете переупорядочивать свой список каким- либо образом, вы можете безопасно использовать индекс в качестве ключа.

Однако, если вы намерены изменить порядок списка (или просто на всякий случай), я бы сгенерировал уникальные идентификаторы для ваших сущностей, если ранее не существовало уникальных идентификаторов, которые вы могли бы использовать.

Быстрый способ добавить идентификаторы — просто отобразить список и присвоить индекс каждому элементу при первом получении (или создании) списка .

```js
const myItemsWithKeys = myItems.map((item, index) => { ...item, key: uuidv4()});
```

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +  ]);
**Надо исправить:** Дефолтное значение лучше вынести в константу, т.к значение переиспользуется.

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +  const [buttonClear, setButtonClear] = useState<boolean>(true);
**Надо исправить:** Аналогичная проблема как и у файла list-page.tsx. Там есть подробный комментарий что можно сделать.

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +    }
**Можно лучше:** Можно упросить с помощью тернарного оператора.

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +    }
**Надо исправить:** Аналогичная проблема как и у файла list-page.tsx. Там есть подробный комментарий что можно сделать.

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +            }
**Надо исправить:** Аналогичная проблема как и у файла list-page.tsx. Там есть подробный комментарий что можно сделать.

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +}
**Можно лучше:** Лучше вынести типы в отдельный файл.

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +  const [arrButton, setArrButton] = useState<boolean>(false);
**Надо исправить:** Аналогичная проблема как и у файла list-page.tsx. Там есть подробный комментарий что можно сделать.

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +  });
**Надо исправить:** Дефолтные значения лучше вынести в отдельную константу.

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +          }
**Можно лучше:** Можно упросить, использовать тернарный оператор.

2022-09-17 11:51 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +  const [arrayElements, setArrayElements] = useState<Array<number[]>>([]);
**Можно лучше:**  Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

2022-09-18 16:50 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец, почти все прошлые замечания были исправлены!**

### **Замечания, которые нужно исправить:**

- Помните что в коде тоже есть замечания которые нужно исправить, и которые остались с прошлого ревью. Если у вас будут вопросы связанные с комментариями, с радостью постараюсь на них ответить.

- Нужно исправить баг. На странице "Связный список" если нажать на "добавить в head" или "добавить в tail", и при этом в поле значения будет не число, то список перестанет отображаться. Хотя он должен принимать любой символ.


### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-18 16:50 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    Number(e.target.value) > maxLength ? setDisabled(true) : setDisabled(false);
**Можно лучше:** Можно написать немного короче.
```js 
setDisabled(Number(e.target.value) > maxLength);
```
А лучше написать вот так.
```js 
const isNotCorrectValue = Number(e.target.value) > maxLength

setDisabled(isNotCorrectValue);
```

2022-09-18 16:50 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const maxLength = 19;
**Надо исправить:**
имена констант принято записывать в стиле UPPER_CASE. И лучше вынести их за пределы компонента, чтобы они не создавались каждый раз заново, при ререндере.

2022-09-18 16:50 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +              <div className={styles[classText]} key={uuidv4()}>
**Надо исправить:** Такая генерация key, может вызвать ошибку, т.к при каждом ререндере key будет всегда новый. Каждый раз, когда изменяется ключ компонента, React будет [создавать новый экземпляр компонента, а не обновлять текущий](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key) , поэтому для повышения производительности использование Math.random() будет, мягко говоря, неоптимальным.

Кроме того, если вы каким-либо образом переупорядочиваете свой список компонентов, использование индекса в качестве ключа также не будет полезным, поскольку согласовщик React не сможет просто перемещаться по существующим узлам DOM, связанным с компонентами, вместо этого ему придется повторно -создать DOM-узлы для каждого элемента списка, которые, опять же, будут иметь неоптимальную производительность.

Но повторюсь, это будет проблемой только в том случае, если вы будете переупорядочивать список, поэтому в вашем случае, если вы уверены, что не будете переупорядочивать свой список каким- либо образом, вы можете безопасно использовать индекс в качестве ключа.

Однако, если вы намерены изменить порядок списка (или просто на всякий случай), я бы сгенерировал уникальные идентификаторы для ваших сущностей, если ранее не существовало уникальных идентификаторов, которые вы могли бы использовать.

Быстрый способ добавить идентификаторы — просто отобразить список и присвоить индекс каждому элементу при первом получении (или создании) списка .

```js
const myItemsWithKeys = myItems.map((item, index) => { ...item, key: uuidv4()});
```

2022-09-18 16:50 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +let list: ILinkedList<number> = new LinkedList<number>();
**Надо исправить:** Если переменная не перезаписывается, то её следует объявлять как `const`, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как `const`

2022-09-18 16:50 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    inputIndexValue !== "" && listArr ? setDelByIndex(false) : setDelByIndex(true);
**Можно лучше:** Лучше написать вот так.
```js 
if(inputIndexValue !== "") {
 setAddByIndex(inputValue === "");
 setDelByIndex(!!listArr);
}
```

2022-09-18 16:50 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    }
**Можно лучше:** Лучше написать вот так.
```js 
setAddHead(inputValue === "");
setAddTail(inputValue === "");
```

2022-09-18 16:50 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    }
**Можно лучше:** Указал выше как можно написать проще.

2022-09-18 17:28 UTC, AlexAfanasiev1980 commented on src/components/list-page/list-page.tsx
> +  const [loaderDelTail, setLoaderDelTail] = useState<boolean>(false);
Здравствуйте. Я пробовал применить объекты, но не смог добиться, чтобы они перезаписывались. Что-то неправильно делал, наверное. Времени не оставалось, чтобы разобраться до дедлайна. Поэтому оставил этот вариант. На рефакторинг, чтобы разобраться в проблеме уйдет несколько дней... Это обязательно к исправлению?

2022-09-18 17:29 UTC, AlexAfanasiev1980 commented on src/components/list-page/list-page.tsx
> +  const [loaderDelTail, setLoaderDelTail] = useState<boolean>(false);
Я правильно понял, что именно это неисправленное замечание с прошлого ревью Вы имели ввиду?

2022-09-18 17:46 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +  const [loaderDelTail, setLoaderDelTail] = useState<boolean>(false);
Да, сейчас покажу вариант исправления.

![image](https://user-images.githubusercontent.com/70164458/190921052-5e7d6c79-d8d5-452d-9055-e9dcf0023626.png)

![image](https://user-images.githubusercontent.com/70164458/190921072-33158bd6-5d9a-4b2a-85bf-b389c580b11b.png)

```js
setButtonsStatus((prevState) => {
  prevState,
  addInHead: {
    disabled: false,
    loading: true,
  },
});
```

2022-09-19 12:21 UTC, AlexAfanasiev1980 commented on src/components/list-page/list-page.tsx
> +  const [loaderDelTail, setLoaderDelTail] = useState<boolean>(false);
Спасибо, понятнее стало, что нужно сделать.

2022-09-20 11:15 UTC, ArslanDev666 approved these changes
## Code Review

### **Вы молодец, код стал более лаконичным и понятным, продолжайте в том же духе!**

2022-09-20 13:42 UTC, merged